categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
  - title: 'Major Changes'
    labels:
      - 'major'
  - title: 'Minor Changes'
    labels:
      - 'enhancement'
  - title: 'Bugfixes'
    labels:
      - 'bug'
  - title: 'Removals'
    labels:
      - 'removed'
  - title: 'Documentation updates'
    labels:
      - 'docs'
  - title: 'Dependencies updates'
    labels:
      - 'update'

exclude-labels:
  - 'skip-changelog'

template: |
  ## Changes

  $CHANGES
