# Specify requirement files by hand
requirements:
  - "requirements.txt"
  - "{{cookiecutter.project_slug}}/requirements/base.txt"
  - "{{cookiecutter.project_slug}}/requirements/local.txt"
  - "{{cookiecutter.project_slug}}/requirements/production.txt"
