name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script:
          - name: Test results
            run: tox -e py38
          - name: Black template
            run: tox -e black-template
          - name: Basic Docker
            run: sh tests/test_docker.sh
          - name: Extended Docker
            run: sh tests/test_docker.sh use_celery=y use_drf=y js_task_runner=Gulp
          - name: Bare metal
            run: sh tests/test_bare.sh use_celery=y use_compressor=y

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U tox
      - name: ${{ matrix.script.name }}
        run: ${{ matrix.script.run }}
