name: Update Contributors

on:
  push:
    branches:
      - master
      - auto-generate-contributors

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update list
      run: python scripts/update_contributors.py

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update Contributors
        file_pattern: CONTRIBUTORS.md
